### ISSUE TITLE
Connect to remote SuperCollider

### ISSUE THREAD

**Issue by Kajvdh** [Sciss/ScalaCollider#62]
Hey there,

I have a SuperCollider set-up running on a Raspberry Pi and I used to connect to it using the overtone libraries in Clojure. 

However, I was searching for a Java/Scala API to do so and I've stumbled upon this project. However, it seems that this library starts it own scsynth instance? Isn't is possible to connect to a remote (my Pi) instance of scsynth and supercollider using this framework?

I hope someone can help me out, thanks a lot!

Greetings,

Kaj

**Comment by Sciss** [comment]
Hi,

Yes, you can connect to an existing server. You can use `Server.connect()` for that. I haven't tested it much, so let me know if there are any issues.

    val c = Server.Config()
    c.addr = new InetSocketAddress("raspi-ip", port)
    Server.connect(config = c)

See also http://sciss.github.io/ScalaCollider/latest/api/#de.sciss.synth.Server$

Raspberry Pi is a great platform that I'm also just discovering. I would be interested to learn about your project.

**Comment by Kajvdh** [comment]
Thanks for the fast reply!

I tried your code, but it doesn't seem to work for me:

```scala
def main(args: Array[String]): Unit = {
    val cfg = Server.Config()
    cfg.host = "192.168.0.198"
    cfg.port = 4555
    cfg.transport = TCP

    val conn = Server.connect(config = cfg) {
        case ServerConnection.Running(s) => {
            println("It works!")

            play {
            val f = LFSaw.kr(0.4).madd(24, LFSaw.kr(8, 7.23).madd(3, 80)).midicps
            CombN.ar(SinOsc.ar(f) * 0.04, 0.2, 0.2, 4)
            }
        }
        case _ => println("Something went wrong!")
    }
    conn
}
```

It's not printing anything, so I assume that I'm doing something wrong. I must admit that I am completely new to this library so I don't know if there is any other boilerplate that I need to run. I'm just running this code within a clean sbt project, and I've added the dependency of this library.

If you're interested in running supercollider on a RPi, check out this thread: http://sam.aaron.name/2012/11/02/supercollider-on-pi.html (check out my reaction as well, since some information within the post is outdated)

**Comment by Sciss** [comment]
It's definitely strange that it doesn't print anything. Code looks correct to me. I can only imagine that the network connection hangs forever, difficult to say. So you start the server with `scsynth -t 4555`? I can try to see if I get it to work later today, when I'm in the studio (I'm setting up some Pis there).

**Comment by Kajvdh** [comment]
I've tried both UDP and TCP. 

So for TCP I started the scsynth with `scsynth -t 4555`, and set the `transport` value to `TCP`.
For UDP I started the scsynth using `scsynth -u 4555`, and set the `transport` value to `UDP`.

But no output results in both of these attempts.

**Comment by Sciss** [comment]
I tried myself now. I think you actually have an exception thrown, perhaps it's just not printed. The exception is likely `java.net.SocketException: Invalid argument` which happens because you have not specific the local (client) network adaptor, and I think that means it defaults to loopback (127.0.0.1) which cannot connect to a remote address.

You can explicitly set the local socket address using the `clientConfig` argument. Unfortunately the settings are a bit asymmetric - while in the server config you specify `hostname` and `port`, here you have `addr: Option[InetSocketAddress]`. But that's just a cosmetic issue.

The following code worked for me:

```scala
val local = Client.Config()
local.addr = Some(new java.net.InetSocketAddress("192.168.0.2", 0))
val remote = Server.Config()
remote.host = "192.168.0.11"
remote.port = 55555
remote.transport = TCP
Server.connect(config = remote, clientConfig = local) {
  case ServerConnection.Running(s) =>
    play(target = s.defaultGroup) {
      SinOsc.ar(SinOsc.ar(Seq(1, 1.1)).linexp(-1, 1, 400, 1000)) * 0.1
    }
  
  case status => println(s"Remote: $status")
}
```

This is with me having given the Raspberry Pi the fixed IP address 192.168.0.11 and the laptop (client) the fixed IP address 192.168.0.2. You can use a port of zero for the client, in that case ScalaCollider will pick a random available port. I also don't know about the port ranges that are enabled by default - I always use the 5-digit range. You could try with the original SuperCollider server port number 57120 as well.

**Comment by Kajvdh** [comment]
Thank you very much for all the effort you've put into helping me out.
Your theory about the application using the wrong network adapter makes sense to me. I've set the `clientConfig` argument within the connect function and that did the trick.

It works perfectly now, thanks a lot!

**Comment by Sciss** [comment]
Glad I could help!
